### PR TITLE
ABX-6289

### PR DESCRIPTION
**Pull request by esusarra**
Removed fees that are not distributed to customers

### CODE REVIEW

**Comment by MilesNorton** [comment]
I feel like this is redundant? could you please confirm?

**Comment by esusarra** [comment]
Hi, Mr. Miles according to the tests my partner conducted locally there was no redundancy in the data

**Comment by MilesNorton** [comment]
ok, i will keep this as a pr until the sprint goes ahead for this ticket. at this point the ticket in jira is in the backlog for now

**Comment by esusarra** [comment]
Perfect, I'll be attentive

**Pull request closed without merging**
